name: Crystal Visions
favicon: null
layout_spectrum: 0.6989882
typography_spectrum: 0.1644182
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5C3077'
    - '#AC77CF'
    - '#FA8803'
    - '#9A3901'
    - '#FFE876'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
