name: Crystal Visions
favicon: null
layout_spectrum: 0.9479103130288422
typography_spectrum: 0.36601885687559843
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4120503328740597
  lightness: 0.4613791946321726
  saturation: 0.6329040238633752
  rhythmicContrast: 0.9055722879711539
purpose: []
