name: Crystal Visions
favicon: null
layout_spectrum: 0.7149
typography_spectrum: 0.50317
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8a6bb0'
    - '#c9b0e2'
    - '#e5deee'
    - '#301267'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
